version: "0.1"
environments:
  - name: master
    branch: master
    mode: pull-request
apps:
  - name: flycode-vue-example-app
    path: ""
    text-resources:
      - path: src/langs/*.json
        format: flat-key-value
      - path: "*.vue"
        format: vue-hardcoded
